# Generated by Django 4.2.10 on 2024-02-23 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
